version: '3'

volumes:
  pgdata:
    driver: local

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: sh -c "node dist/migrate.js && node dist/index.js"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
